variables:
  IMAGE: "infladoor/wiredoor-cli"

stages:
  - build
  - test
  - release

include:
  - project: 'wiredoor/ci-cd'
    ref: main
    file: '/templates/docker_build.gitlab-ci.yaml'
  - project: 'wiredoor/ci-cd'
    ref: main
    file: '/templates/go_test.gitlab-ci.yaml'
  - project: 'wiredoor/ci-cd'
    ref: main
    file: '/templates/go_pkgs.gitlab-ci.yaml'
  - project: 'wiredoor/ci-cd'
    ref: main
    file: '/templates/docker_release.gitlab-ci.yaml'
